import type { Metadata } from "next";
import { Rubik, Ubuntu } from "next/font/google";
import "./globals.css";

const rubikSans = Rubik({
  variable: "--font-family-rubik",
  subsets: ["latin"],
});
const ubuntuSans = Ubuntu({
  variable: "--font-family-ubuntu",
  weight: "300",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
