import type { Metadata } from "next";
import { Rubik, Ubuntu } from "next/font/google";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "./globals.css";
import { createClient } from "@/prismicio";
import { SliceZone } from "@prismicio/react";
import { components } from "@/slices";

const rubikSans = Rubik({
  variable: "--font-family-rubik",
  subsets: ["latin"],
});
const ubuntuSans = Ubuntu({
  variable: "--font-family-ubuntu",
  weight: "300",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const client = createClient();
  const page = await client.getSingle("footer");
  return (
    <html lang="en">
      <body className={`${rubikSans.variable} ${ubuntuSans.variable} container mx-auto p-2`}>
        <div>{children}</div>
        <SliceZone slices={page.data.slices} components={components} /> {/* FOOTER HERE*/}
      </body>
    </html>
  );
}
