// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blogslice: dynamic(() => import("./Blogslice")),
  contact: dynamic(() => import("./Contact")),
  footer: dynamic(() => import("./Footer")),
  hero: dynamic(() => import("./Hero")),
  my_work: dynamic(() => import("./MyWork")),
  navbar: dynamic(() => import("./Navbar")),
  parallex: dynamic(() => import("./Parallex")),
  portofolio: dynamic(() => import("./Portfolio")),
  socials: dynamic(() => import("./Socials")),
  statistics: dynamic(() => import("./Statistics")),
  testimonials: dynamic(() => import("./Testimonials")),
};
